// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace smakchet.dal.Models;

public partial class ErrorLog
{
    public int Id { get; set; }

    public string Source { get; set; }

    public string Action { get; set; }

    public int? ReferenceId { get; set; }

    public string ErrorMessage { get; set; }

    public string ErrorCode { get; set; }

    public string Payload { get; set; }

    public bool? IsResolved { get; set; }

    public DateTime? CreatedAt { get; set; }
}