// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace smakchet.dal.Models;

public partial class OrderStatusLog
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int? OldStatus { get; set; }

    public int? NewStatus { get; set; }

    public int? ChangedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int CashierId { get; set; }

    public virtual User Cashier { get; set; }

    public virtual User ChangedByNavigation { get; set; }

    public virtual Order Order { get; set; }
}