// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace smakchet.dal.Models;

public partial class OrderItem
{
    public int Id { get; set; }

    public string Number { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? SizeId { get; set; }

    public int? IceLevelId { get; set; }

    public int? SugarLevelId { get; set; }

    public int? CoffeeLevelId { get; set; }

    public int? VariationId { get; set; }

    public virtual CoffeeLevel CoffeeLevel { get; set; }

    public virtual Ice IceLevel { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual Size Size { get; set; }

    public virtual Sugar SugarLevel { get; set; }

    public virtual Variation Variation { get; set; }
}