// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace smakchet.dal.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int? Method { get; set; }

    public decimal? Amount { get; set; }

    public int? Status { get; set; }

    public string ReferenceCode { get; set; }

    public int CashierId { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Cashier { get; set; }

    public virtual Order Order { get; set; }
}