// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace smakchet.dal.Models;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Profile { get; set; }

    public string PasswordHash { get; set; }

    public string ProfileImage { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<OrderStatusLog> OrderStatusLogCashiers { get; set; } = new List<OrderStatusLog>();

    public virtual ICollection<OrderStatusLog> OrderStatusLogChangedByNavigations { get; set; } = new List<OrderStatusLog>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}